id: P004359
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:14:45.005570
source_metadata:
  id: bdr:W1AC325
  title: 'དཔལ་དྭགས་པོ་ཟླ་འོད་གཞོན་ནུའི་ཚོགས་ཆོས་དང་ཞུས་ལན་ཕྱོགས་བསྡུས་མཉམ་མེད་བླ་མའི་ཞལ་སྐྱིན། '
  author: ''
  volumes:
    0618cbdb27e7404a8ff171ee302f84c7:
      image_group_id: I2PD18336
      title: ''
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
