id: P004359
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC325
  title: 'དཔལ་དྭགས་པོ་ཟླ་འོད་གཞོན་ནུའི་ཚོགས་ཆོས་དང་ཞུས་ལན་ཕྱོགས་བསྡུས་མཉམ་མེད་བླ་མའི་ཞལ་སྐྱིན། '
  author: ''
  volumes:
    0618cbdb27e7404a8ff171ee302f84c7:
      image_group_id: I2PD18336
      title: ''
      volume_number: 1
      total_pages: 314
